### ISSUE TITLE
EP3: WARN bevy_ecs::world: error[B0003]: Could not despawn entity `xxxxx` because it doesn't exist in this World.

### ISSUE THREAD

**Issue by jsjtxietian** [marcelchampagne/bevy-basics#3]
Hi thank you for your great work, I learnt a lot from it and really love it ❤️ 

When following ep3 I noticed that the error `WARN bevy_ecs::world: error[B0003]: Could not despawn entity `xxxxx` because it doesn't exist in this World.` is flushing, I have seen your answer at the youtube comments but I don't quite get it.

You mentioned that :
"In despawn_far_away_entities, we have a Query<(Entity, &GlobalTransform)>, which queries all entities with global transforms. This is true for multiple entities spawned from the GLB model (bullets, asteroids, etc.) using SceneBundle. As such, commands.entity(entity).despawn_recursive() is going to despawn entire hierarchies. However, this approach leads to redundant child despawns, but these are inconsequential and can be disregarded."

I don't understand why this approach will lead to redundant child despawns,  in `despawn_far_away_entities`, we did the query exactly once per frame for all entity with SceneBundle, why there will be duplicate despawn ? 

Thanks in advance for your explaination!

**Comment by marcelchampagne** [comment]
@jsjtxietian In Bevy almost everything has a Transform component. With a SceneBundle, you are actually spawning multiple entities in a hierarchy. For a GLTF file, there is going to be a root node and child nodes (e.g. https://raw.githubusercontent.com/KhronosGroup/glTF/5615a3a91504015c47bb07b0ee4707351f93d4e3/specification/2.0/figures/objects.svg). Each of these nodes are represented in the ECS world as a separate entity, each with its own components (e.g. Transform).

As such, let's say we have entities A, B, and C. Imagine B and C are child nodes of entity A. Then, if we iterate over the entities in order, calling commands.entity(A).despawn_recursive() is going to also despawn B and C, because despawn_recursive tells Bevy to despawn the entity and the children of that entity. However, we'll also explicitly call commands.entity(B).despawn_recursive() in the next iteration of the loop. Thus, we are going to get the warn when the commands are applied, since B was already despawned by the previous command.

Maybe your confusion is around what the query is iterating. You mentioned "we did the query exactly once per frame for all entity with SceneBundle", but that's not exactly true. In `despawn_far_away_entities` we are querying for everything with a GlobalTransform, which means we'll iterate through multiple entities for a single SceneBundle.

Let me know if that makes sense!

**Comment by jsjtxietian** [comment]
> there is going to be a root node and child nodes

 I see. I assumed that a single gltf only spawns one entity that represents the whole model, so previously I wondered why we have parent/child relationship in the game. It makes sense that "Each of these nodes are represented in the ECS world as a separate entity". 

Thanks a lot !
